services:
  car_db:
    image: postgres:latest
    container_name: car_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_db
    ports:
      - "5432:5432"
    volumes:
      - car_db_data:/var/lib/postgresql/data
      -